# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
name: Build and Push Docker Containers

on:
  schedule:
    - cron: '33 7 * * 0'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env: 
      DOCKER_USERNAME: barrowwight

    strategy:
      matrix: 
        buildroot-version: [2021.11, 2022.02]
      
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Base Image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          tags: |
            ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-base
            ghcr.io/${{ github.actor }}/d1-buildroot:${{ matrix.buildroot-version }}-base
          push: false
          target: base
          load: true
          build-args: BUILDROOT_VERSION=${{ matrix.buildroot-version }}

      - name: Build Toolchain Container
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          tags: |
            ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-toolchain
            ghcr.io/${{ github.actor }}/d1-buildroot:${{ matrix.buildroot-version }}-toolchain
          push: false
          target: toolchain
          load: true
          build-args: BUILDROOT_VERSION=${{ matrix.buildroot-version }}

      - name: Build Prebuilt Container
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          tags: |
            ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-prebuilt
            ghcr.io/${{ github.actor }}/d1-buildroot:${{ matrix.buildroot-version }}-prebuilt
          push: false
          target: prebuilt
          load: true
          build-args: BUILDROOT_VERSION=${{ matrix.buildroot-version }}

        # No need to scan other containers, since they are a subset of prebuilt
      - name: Scan Prebuilt Container with Snyk
        uses: snyk/actions/docker@0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          image: ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-prebuilt
          args: --file=Dockerfile

      - name: Upload Snyk Result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

        # Rootfs.ext4 is a symlink to rootfs.ext2.
        # For windows users, I am deleting rootfs.ext4 symlink and copying rootfs.ext2
      - name: Get Target Images from Container
        run: |
          docker create --name testcontainer ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-prebuilt
          docker cp testcontainer:/home/buildroot-${{ matrix.buildroot-version }}/output/images d1-image
          rm d1-image/rootfs.ext4 
          cp d1-image/rootfs.ext2  d1-image/rootfs.ext4 
          docker container rm testcontainer
  

      - name: Save Prebuilt Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: d1-image-${{ matrix.buildroot-version }}
          path: d1-image/

      - name: Push Containers to Docker Hub
        run: docker push -a ${{ env.DOCKER_USERNAME }}/d1-buildroot

      - name: Push Containers to GitHub packages
        run: docker push -a ghcr.io/${{ github.actor }}/d1-buildroot
