# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
name: Build Docker Images

on:
  schedule:
    - cron: '33 7 * * 0'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env: 
      DOCKER_USERNAME: barrowwight

    strategy:
      matrix: 
        buildroot-version: [2021.11]
      
    permissions:
      contents: read
      packages: write

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Base Image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: |
            ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-base
            ghcr.io/${{ github.actor }}/d1-buildroot:${{ matrix.buildroot-version }}-base
          push: false
          target: base
          load: true
          build-args: BUILDROOT_VERSION=${{ matrix.buildroot-version }}

      - name: Build Toolchain Container
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: |
            ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-toolchain
            ghcr.io/${{ github.actor }}/d1-buildroot:${{ matrix.buildroot-version }}-toolchain
          push: false
          target: toolchain
          load: true
          build-args: BUILDROOT_VERSION=${{ matrix.buildroot-version }}

      - name: Build Prebuilt Container
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: |
            ${{ env.DOCKER_USERNAME }}/d1-buildroot:${{ matrix.buildroot-version }}-prebuilt
            ghcr.io/${{ github.actor }}/d1-buildroot:${{ matrix.buildroot-version }}-prebuilt
          push: false
          target: prebuilt
          load: true
          build-args: BUILDROOT_VERSION=${{ matrix.buildroot-version }}
